### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by seungsoon97** [gzaber/dtn_web#1]
I am learning about flutter webpage dev. can i use this code? and can i ask about code?

**Comment by gzaber** [comment]
Hi,
of course you can use the code.
If you have any question feel free to ask.

**Comment by seungsoon97** [comment]
I have mission for making webpage about flutter.
i found your code and it is similar to design that i wanna make.
then i tried to put two options, but i can't.
1. put video in webpage's 'home'
2. if click mail address, open in mail program.

I searched many codes in google, but i couldn't add in your code.
can i ask about that 2options?

**Comment by seungsoon97** [comment]
I have mission for making webpage about flutter.
i found your code and it is similar to design that i wanna make.
then i tried to put two options, but i can't.

1. put video in webpage's 'home'
2. if click mail address, open in mail program.
I searched many codes in google, but i couldn't add in your code.
can i ask about that 2options?

**Comment by gzaber** [comment]
1)) you can use video_player package:
https://pub.dev/packages/video_player
YT tutorials where video_player is used:
https://www.youtube.com/watch?v=rJKN_880b-M
https://www.youtube.com/watch?v=ZPdG0mCtTYg

2)) you can use url_launcher package:
https://pub.dev/packages/url_launcher
YT example:
https://www.youtube.com/watch?v=WjYqps8WR9g

**Comment by seungsoon97** [comment]
I tried, but i can't add core code about video and url....

I think it is hard to me handling many classes and files and so on..

In fact, i don't know what start to coding exactly
sadly have no base..

Always thanks, have a good day!
